fix: update Terraform workflow to check EKS cluster existence before applying changes

diff --git a/.github/workflows/first-worflow.yaml b/.github/workflows/first-worflow.yaml
--- a/.github/workflows/first-worflow.yaml
+++ b/.github/workflows/first-worflow.yaml
@@ -44,24 +44,64 @@ jobs:
         run: terraform plan -out=tfplan
         working-directory: EKS/Dev/module_eks
       
-      # Step 7: Terraform Plan
-      - name: Terraform apply  ###if: github.ref == 'refs/heads/main'
-        id: apply
+      # Step 7: Check if EKS cluster already exists
+      - name: Check EKS cluster
+        id: check-cluster
+        continue-on-error: true
         run: |
-          terraform apply --auto-approve=true 
+          aws eks describe-cluster --name first-cluster --region ca-central-1
+          
+      # Step 8: Terraform apply (only if cluster does not exist)
+      - name: Terraform Apply
+        if: steps.check-cluster.outcome == 'failure'
+        run: terraform apply --auto-approve
         working-directory: EKS/Dev/module_eks
-      
-      # Step 8: Update kubeconfig file      
+
+      # Step 9: Update kubeconfig file      
       - name: Update kubeconfig
         run: |
           aws eks update-kubeconfig \
           --region ca-central-1 \
           --name first-cluster
 
-      - name: Depploy role and role binding 
-        run : |
-          kubectl apply -f viewer-cluster-role.yaml
-          kubectl apply -f viewer-cluster-role-binding.yaml
+post-deploy:
+    runs-on: ubuntu-latest
+    needs: create-cluster   # ensures this runs only after cluster creation succeeds
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ca-central-1
+
+      - name: Update kubeconfig
+        run: |
+          aws eks update-kubeconfig \
+          --region ca-central-1 \
+          --name first-cluster
+
+      - name: Deploy role and role binding 
+        run: |
+          # Check ClusterRole
+          if ! kubectl get clusterrole viewer >/dev/null 2>&1; then
+            echo "ClusterRole 'viewer' not found. Creating..."
+            kubectl apply -f viewer-cluster-role.yaml
+          else
+            echo "ClusterRole 'viewer' already exists. Skipping..."
+          fi
+
+          # Check ClusterRoleBinding
+          if ! kubectl get clusterrolebinding my-viewer-binding >/dev/null 2>&1; then
+            echo "ClusterRoleBinding 'my-viewer-binding' not found. Creating..."
+            kubectl apply -f viewer-cluster-role-binding.yaml
+          else
+           echo "ClusterRoleBinding 'my-viewer-binding' already exists. Skipping..."
+          fi
         working-directory: EKS/Dev/yaml_files
 
       - name: Install Helm
